# Generated by Django 6.0.5 on 2026-05-11 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepairRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=128, verbose_name='文件ID')),
                ('mode', models.CharField(choices=[('colorize', '黑白上色'), ('repair', '破损修复'), ('enhance', '清晰度增强'), ('denoise', '智能去噪')], max_length=20, verbose_name='修复模式')),
                ('mode_name', models.CharField(default='', max_length=50, verbose_name='模式名称')),
                ('platform', models.CharField(default='', help_text='baidu/tencent/replicate', max_length=50, verbose_name='AI平台')),
                ('cost_time', models.FloatField(default=0.0, verbose_name='耗时(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('ip', models.CharField(blank=True, default='', max_length=50, verbose_name='IP地址')),
                ('is_success', models.BooleanField(default=True, verbose_name='是否成功')),
                ('error_msg', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('source_path', models.CharField(blank=True, default='', max_length=255, verbose_name='源文件路径')),
                ('result_path', models.CharField(blank=True, default='', max_length=255, verbose_name='结果文件路径')),
                ('status', models.CharField(choices=[('pending', '等待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='completed', max_length=20, verbose_name='处理状态')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '修复记录',
                'verbose_name_plural': '修复记录列表',
                'db_table': 'repair_records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='idx_user_created'), models.Index(fields=['mode'], name='idx_mode'), models.Index(fields=['platform'], name='idx_platform'), models.Index(fields=['is_success'], name='idx_success'), models.Index(fields=['file_id'], name='idx_file_id')],
            },
        ),
    ]
