# Generated by Django 6.0.5 on 2026-05-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True, verbose_name='日期')),
                ('total_repairs', models.IntegerField(default=0, verbose_name='总修复次数')),
                ('unique_users', models.IntegerField(default=0, verbose_name='独立用户数')),
                ('new_users', models.IntegerField(default=0, verbose_name='新用户数')),
                ('mode_colorize', models.IntegerField(default=0, verbose_name='黑白上色次数')),
                ('mode_repair', models.IntegerField(default=0, verbose_name='破损修复次数')),
                ('mode_enhance', models.IntegerField(default=0, verbose_name='清晰度增强次数')),
                ('mode_denoise', models.IntegerField(default=0, verbose_name='智能去噪次数')),
                ('platform_baidu', models.IntegerField(default=0, verbose_name='百度AI次数')),
                ('platform_tencent', models.IntegerField(default=0, verbose_name='腾讯云次数')),
                ('platform_replicate', models.IntegerField(default=0, verbose_name='Replicate次数')),
                ('avg_cost_time', models.FloatField(default=0.0, verbose_name='平均耗时(秒)')),
                ('errors', models.IntegerField(default=0, verbose_name='错误次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '每日统计',
                'verbose_name_plural': '每日统计数据',
                'db_table': 'daily_stats',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HourlyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('hour', models.IntegerField(help_text='0-23', verbose_name='小时')),
                ('repairs', models.IntegerField(default=0, verbose_name='修复次数')),
                ('mode_colorize', models.IntegerField(default=0, verbose_name='黑白上色')),
                ('mode_repair', models.IntegerField(default=0, verbose_name='破损修复')),
                ('mode_enhance', models.IntegerField(default=0, verbose_name='清晰度增强')),
                ('mode_denoise', models.IntegerField(default=0, verbose_name='智能去噪')),
            ],
            options={
                'verbose_name': '每小时统计',
                'verbose_name_plural': '每小时统计数据',
                'db_table': 'hourly_stats',
                'ordering': ['date', 'hour'],
                'unique_together': {('date', 'hour')},
            },
        ),
    ]
