# Generated by Django 6.0.5 on 2026-05-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(help_text='微信openid', max_length=64, primary_key=True, serialize=False, verbose_name='用户ID')),
                ('union_id', models.CharField(blank=True, default='', max_length=64, verbose_name='UnionID')),
                ('nickname', models.CharField(blank=True, default='', max_length=100, verbose_name='昵称')),
                ('avatar', models.URLField(blank=True, default='', verbose_name='头像URL')),
                ('free_remaining', models.IntegerField(default=3, verbose_name='剩余免费次数')),
                ('is_member', models.BooleanField(default=False, verbose_name='是否会员')),
                ('member_expire', models.DateTimeField(blank=True, null=True, verbose_name='会员过期时间')),
                ('total_repairs', models.IntegerField(default=0, verbose_name='总修复次数')),
                ('status', models.CharField(choices=[('active', '正常'), ('banned', '已禁用')], default='active', max_length=20, verbose_name='状态')),
                ('is_admin', models.BooleanField(default=False, verbose_name='是否管理员')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='最后登录')),
                ('session_key', models.CharField(blank=True, default='', max_length=64, verbose_name='SessionKey')),
                ('raw_data', models.TextField(blank=True, default='', verbose_name='原始用户信息(JSON)')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户列表',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
    ]
